### ISSUE TITLE
Drawbacks of using this gem in production

### ISSUE THREAD

**Issue by manuelpuyol** [anycable/anycable-rack-server#5]
Hey!

I'm planning to use AnyCable for my application, but I'm having some trouble implementing a good deployment structure.

Since my app is hosted in Heroku I ran in this comment in the doc:

> The only way (for now) to run AnyCable applications on Heroku is to have two separate applications sharing some resources: the first one is a typical web application responsible for general HTTP and the second contains AnyCable WebSocket and RPC servers.

I feel like creating a second application to run AnyCable will be harder to mantain, since I have to sync both deployments in case I change DB structure or code that is used by both of them.
Right now I have a quite large deploy (building rails + webpacker) and it's not hard to the apps become out of sync due to the big variance on build times.

At the end of the documentation, I saw the alternative to use this gem and even though it states there:

> it has the same architecture involving the RPC server, and thus provides the same experience as another, standalone, AnyCable implementations.

Which makes me think it should not be a problem in production, but the first line in this repo is:

> AnyCable-compatible Rack hijack based Ruby Web Socket server designed for **development and testing purposes**.

Which makes me scared to use it live.

Do you have any idea of the real drawbacks of using this gem in production?

**Comment by palkan** [comment]
Hey @manuelpuyol! Hope you're doing well.

Sorry, I haven't been subscribed to this repo notifications, and just found this issue. It's never too late)

> Do you have any idea of the real drawbacks of using this gem in production?

The WebSocket server implementation shipped with the gem is very-straightforward: we spawn a thread for every connection. This approach is very extensive in terms of memory usage and not really efficient from the performance point of view due to GVL.
It works OK for, maybe, ~100 connections (that's why "designed for development and testing purposes").

> I feel like creating a second application to run AnyCable will be harder to mantain, since I have to sync both deployments in case I change DB structure or code that is used by both of them

Please, check out our updated documentation on Heroku deployment: https://docs.anycable.io/v1/#/deployment/heroku

We tried to provide as many tips as possible to make using AnyCable on Heroku less complex.
